FROM node:20-alpine
WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/webhook ./apps/webhook

RUN npm install 

RUN npm run generate:db
RUN npx turbo build --filter=webhook

EXPOSE 3002
CMD [ "npm","run","start:webhook"]