FROM node:20-alpine
WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/http ./apps/http

RUN npm install 
RUN npm run generate:db
RUN npx turbo build --filter=http...

EXPOSE 3001

CMD [ "npm","run","start:backend"]